name: AdvancedRank
version: @version@
main: de.blocki.advancedrank.main.Main
authors: [ blocki ]
description: /rank plugin for Minecrfat Java Version 1.8 - 1.16
api-version: 1.16
depend:
  - LuckPerms
commands:
  rank:
    description: List all commands
    aliases:
      - rang